minio:
  endpoint: localhost:9000
  credential: minioadmin:minioadmin
  accessKey: abcd123456
  secretKey: abcd123456
  useSSL: false
  dir:
    bucketName: test
postgres:
 dsn: "host=localhost user=postgres password=postgres dbname=playground port=5432 sslmode=disable TimeZone=Asia/Shanghai"
 username: postgres
 password: postgres
rabbitmq:
 url: amqp://guest:guest@localhost:5672/
server:
 port: 8080